### ISSUE TITLE
Parsing fails on certain dates and times.

### ISSUE THREAD

**Issue by madogai** [jedwards1211/tell-me-when#1]
Hello. It is a very useful library.

However, when I tried to use it, I got parseError in the following cases.

```ts
tellMeWhen('2001/10/10');.
```

It seems that 10/10 is not parsed correctly, since '2001/10/11' gives a normal result.

Also, the following cases also seem to result in parseError.
```ts
tellMeWhen('2000/1/1 21:00');
```

It seems that parsing after 20:00 fails because '2000/1/1 19:00' gives a normal result.

**Comment by jedwards1211** [comment]
Thanks! You were quite right, my regexes for month and hour numbers were bad.  Fix should be released by CI in a moment!

**Comment by jedwards1211** [comment]
@madogai it's ironic that you're my first stargazer, since this library is designed for US English right now and looks like you're in Japan.  If you have any interest in implementing Japanese Date/Time expression for this lib or a fork, I'm happy to help you understand how the parsing system works!

**Comment by madogai** [comment]
@jedwards1211 Thanks for fixing the bug!

In Japan, date and time expressions are not much different from those in English. Especially in programming.
Therefore, I think there is no problem for English.

However, since you might be interested, I also describe time expressions in Japanese.

'2024-12-28 10:20:30' is expressed as follows in Japanese. '2024年12月28日10時20分30秒'.

If I have time, I will also fork and create a pull request!

**Comment by jedwards1211** [comment]
Okay, I do think it would be neat to support many different locales someday, but I think it would be better to get contributions from native speakers rather than attempting anything myself, since the goal is to support common expressions like "the day after tomorrow", "two hours ago" etc. in a given language/locale as well as absolute dates/times.

**Comment by madogai** [comment]
It's true that idiomatic expressions are better suited to native speakers.

For example, In Japanese, "tomorrow" is "明日" and "the day after tomorrow" is "明後日", so I think the rules are difficult to understand.

I'll try to find some time to use it, as it may be useful for my program. (But please don't expect too much.)
